
name: "CAI Post Deployment"

on:
  workflow_dispatch:
    inputs:
      pod_id:
        type: choice
        description: 'Pod ID in which BPR has to trigger'     
        required: true
        options:
        - mdmnext-prod-apse1
        - mdmnext-prod-azemc1
        - mdmnext-prod-aznttjp1
        - mdmnext-prod-azusw3
        - mdmnext-prod-emw1
        - mdmnext-prod-nac1
        - mdmnext-prod-uk1
        - mdmnext-prod-use2
        - mdmnext-prod-use2s1
        - mdmnext-prod-use4
        - mdmnext-prod-use4s1
        - mdmnext-prod-use6
        - mdmnext-prod-usw3
        - mdmnext-prv-c360
        - mdmnext-prv-c360s1
        - mdmnext-prv-c360s2
        - mdmnext-stage-azusw1
        - mdmnext-stage-pod1s2
        - mdmnext-stg-pod1
        - mdmnext-stg-pod1s1
      cai_username:
        description: "CAI Username"
        required: true
      cai_password:
        description: "CAI Password"
        required: true
        
jobs:        
  source_activate:
    name: Testing on ${{ github.event.inputs.pod_id }}
    runs-on: ${{ github.event.inputs.pod_id }}
    outputs:
      working-directory: ${{ steps.source_activate.outputs.working-directory }}
    steps:      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0     
          token: ${{ github.token }}   
        
      - name: Source activate
        id: source_activate
        env:
          folder_id: ${{ github.event.inputs.pod_id }}
          TERM: xterm
        run: | 
          sudo chmod -R 777 ${{ github.workspace }}
          cat <<EOF | bash
          [[ ":$PATH:" != *":\$(pwd):"* ]] && PATH="\$(pwd):${PATH}"
          source activate "$folder_id" 
          ./mops build mdm
          cd build/$(cat "$folder_id"/env | grep "POD_ID" | awk -F "=" '{print $2}' | tr -d '"')/mdm
          echo ::set-output name=working-directory::"build/$(cat "$folder_id"/env | grep "POD_ID" | awk -F "=" '{print $2}' | tr -d '"')/mdm"
          EOF
        continue-on-error: false
        
  cai_pd:
    name: CAI Post Deployment
    runs-on: ${{ github.event.inputs.pod_id }}
    needs: [source_activate]
    steps:
      - name: CAI Post Deployment
        env:
          CAI_ADMIN_USERNAME: ${{ github.event.inputs.cai_username }}
          CAI_ADMIN_PASSWORD: ${{ github.event.inputs.cai_password}}
          TERM: xterm
          working-directory: ${{ needs.source_activate.outputs.working-directory }}
        run: |
          source activate ${{ github.event.inputs.pod_id }} 
          cd ${{ env.working-directory}}
          ./bin/tools/run-cai-post-deploy.sh
        continue-on-error: false

  
        
