name: Start Pipeline
on:
  push:
    branches:
      - main

jobs:
  call-sub-workflow:
    uses: sriram-demo/demo/actions/workflows/trigger-test.yaml@main
    with:
      release_type: mdmnext-prod-nac1
