
name: "Testing package"

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:        
  check_pr_labels:
    if: github.event_name == 'push' #
    runs-on: ubuntu-latest
    name: EBF Label check
    outputs:
      status: ${{ steps.check_pr_labels.outputs.result }}
      labels: ${{ steps.check_pr_labels.outputs.labels }}
      matrix: ${{ steps.out.outputs.matrix }}
    steps:
    - name: Check
      id: check_pr_labels
      uses: Srirammkm/check-labels@main
      with:
        github-token: ${{ secrets.TOKEN }}
        labels: '["adhoc-task"]'
      continue-on-error: true
      
    - name: All Labels
      id: out
      run: |
        jobs='${{ steps.check_pr_labels.outputs.jobs }}'
        echo $jobs
        echo "matrix={\"include\":$jobs}" >> $GITHUB_OUTPUT
    - name: Print ouptut
      run: |
        echo ${{ steps.out.outputs.matrix }}
  getpod_master:
    if: github.event_name == 'push'
    name: Get POD ID
    runs-on: ubuntu-latest
    needs: check_pr_labels
    outputs:
      folder_id_master: ${{ steps.folder_id_master.outputs.pod_id}}
    steps:      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0     
          token: ${{ github.token }}    

      - name: Get Pod ID for master
        id: folder_id_master
        run: |
         ids_master=''
         for i in `git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "**/*" |  awk -F '/' '{print $1}' | sort | uniq -u`
         do
         ids_master+={'"id_master":"'$i'"},'
         done
         ids_master=${ids_master%?}
         echo $ids_master
         echo "pod_id=$ids_master" >> $GITHUB_OUTPUT
        continue-on-error: true
  job:
    name: ${{ matrix.job_name }}
    needs: [check_pr_labels, getpod_master]
    runs-on: ${{ needs.getpod_master.outputs.folder_id_master }}
    environment:
      name: R2022.11.S
    timeout-minutes: 360 # 6 hour timeout
    strategy:
      matrix: ${{ fromJson(needs.check_pr_labels.outputs.matrix) }}
      max-parallel: 1 # Run jobs serially
    steps:
      - name: ${{ matrix.name }}
        env:
          cai_username: ${{ secrets.CAI_ADMIN }}
          cai_password: ${{ secrets.CAI_PASSWORD }}
        run: |
          echo ${{ matrix.command }}
          echo $cai_username
          echo $cai_password
          ${{ matrix.command }}
        
