
name: "Testing package"

on:
  push:
    branches:
      - main
jobs:        
  check_pr_labels:
    if: github.event_name == 'push' #
    runs-on: ubuntu-latest
    name: EBF Label check
    outputs:
      status: ${{ steps.check_pr_labels.outputs.result }}
      labels: ${{ steps.check_pr_labels.outputs.labels }}
      matrix: ${{ steps.out.outputs.matrix }}
    steps:
    - name: Check
      id: check_pr_labels
      uses: Srirammkm/check-labels@main
      with:
        github-token: ${{ secrets.TOKEN }}
        labels: '["adhoc-task"]'
      continue-on-error: true
      
    - name: All Labels
      id: out
      run: |
        jobs='${{ steps.check_pr_labels.outputs.jobs }}'
        echo $jobs
        echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"},{\"project\":\"pass\",\"config\":\"fail\"},{\"project\":\"good\",\"config\":\"bad\"}]}" >> $GITHUB_OUTPUT
    - name: Print ouptut
      run: |
        echo ${{ steps.out.outputs.matrix }}
  job:
    needs: check_pr_labels
    runs-on: ubuntu-latest
    timeout-minutes: 360 # 6 hour timeout
    strategy:
      matrix: ${{ fromJson(needs.check_pr_labels.outputs.matrix) }}
      max-parallel: 1 # Run jobs serially
    steps:
      - run: ${{ fromJson(needs.check_pr_labels.outputs.matrix) }}
        
