
name: "Trigger All Test ${{ github.event.inputs.pod_id }}"

on:
  workflow_dispatch:
    inputs:
      pod_id:
        type: choice
        description: 'Pod ID in which test has to triggered'     
        required: true
        options:
        - mdmnext-prod-aznttjp1
        - mdmnext-prod-nac1
        - mdmnext-prod-uk1
        - mdmnext-stg-pod1
        - mdmnext-stg-pod1s1
        
jobs:        
  source_activate:
    name: Source Activate
    runs-on: ${{ github.event.inputs.pod_id }}
    outputs:
      working-directory: ${{ steps.source_activate.outputs.working-directory }}
    steps:      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0     
          token: ${{ github.token }}   
        
      - name: Source activate
        id: source_activate
        env:
          folder_id: ${{ github.event.inputs.pod_id }}
          TERM: xterm
        run: | 
          sudo chmod -R 777 ${{ github.workspace }}
          cat <<EOF | bash
          [[ ":$PATH:" != *":\$(pwd):"* ]] && PATH="\$(pwd):${PATH}"
          source activate "$folder_id" 
          ./mops build mdm
          cd build/$(cat "$folder_id"/env | grep "POD_ID" | awk -F "=" '{print $2}' | tr -d '"')/mdm
          echo ::set-output name=working-directory::"build/$(cat "$folder_id"/env | grep "POD_ID" | awk -F "=" '{print $2}' | tr -d '"')/mdm"
          echo ::set-output name=mail-host::"$(cat "$folder_id"/mdm/resources/helm/common-config-params.yaml | grep "mail_host" | awk '{print $2}' )"
          EOF
        continue-on-error: true
  c360_test_run:
    if: (needs.source_activate.result == 'success')
    name: C360 test
    runs-on: ${{ github.event.inputs.pod_id }}
    needs: [source_activate]
    steps:
      - name: running c360 test
        env:
          folder_id: ${{ github.event.inputs.pod_id }}
          TERM: xterm
          working-directory: ${{ needs.source_activate.outputs.working-directory }}
        run: |
          source activate "$folder_id" 
          cd ${{ env.working-directory}}
          ./bin/test/platform-tests.sh -t=C360_Certification_Tests
        continue-on-error: true
           
  rdm_test_run:
    if: (needs.source_activate.result == 'success')
    name: RDM test
    runs-on: ${{ github.event.inputs.pod_id }}
    needs: [source_activate]
    steps:
      - name: running RDM test
        env:
          folder_id: ${{ github.event.inputs.pod_id }}
          TERM: xterm
          working-directory: ${{ needs.source_activate.outputs.working-directory }}
        run: |
          source activate "$folder_id" 
          cd ${{ env.working-directory}}
          export RDM_TEST_PROFILE=reduced
          ./bin/test/rdm-integration-tests.sh
        continue-on-error: true
   
  shm_test_run:
    if: (needs.rdm_test_run.result == 'success' || needs.rdm_test_run.result == 'failure')
    name: SHM test
    runs-on: ${{ github.event.inputs.pod_id }}
    needs: [rdm_test_run,source_activate]
    steps:
      - name: running SHM test
        env:
          folder_id: ${{ github.event.inputs.pod_id }}
          TERM: xterm
          working-directory: ${{ needs.source_activate.outputs.working-directory }}
        run: |
          source activate "$folder_id" 
          cd ${{ env.working-directory}}
          ./bin/test/shm-integration-tests.sh
        continue-on-error: true
  
        
