
name: "Monthly Release Manual"

on:
  workflow_dispatch:
    inputs:
      pod_id:
        type: choice
        description: 'Pod ID in which BPR has to trigger'     
        required: true
        options:
        - mdmnext-prod-apse1
        - mdmnext-prod-azemc1
        - mdmnext-prod-aznttjp1
        - mdmnext-prod-azusw3
        - mdmnext-prod-emw1
        - mdmnext-prod-nac1
        - mdmnext-prod-uk1
        - mdmnext-prod-use2
        - mdmnext-prod-use2s1
        - mdmnext-prod-use4
        - mdmnext-prod-use4s1
        - mdmnext-prod-use6
        - mdmnext-prod-usw3
        - mdmnext-prv-c360
        - mdmnext-prv-c360s1
        - mdmnext-prv-c360s2
        - mdmnext-stage-azusw1
        - mdmnext-stage-pod1s2
        - mdmnext-stg-pod1
        - mdmnext-stg-pod1s1
      cai_username:
        description: "CAI Username"
        required: true
      cai_password:
        description: "CAI Password"
        required: true
      release:
        description: "Please enter release file name"
        required: true
      userconfirmation:
        type: choice
        description: "bypass confirmation after each Update stage"
        required: true
        options:
        - manual
        - auto
        
jobs:        
  check_pr_labels:
    if: github.event_name == 'push' #
    runs-on: ubuntu-latest
    name: EBF Label check
    outputs:
      status: ${{ steps.check_pr_labels.outputs.result }}
      labels: ${{ steps.check_pr_labels.outputs.labels }}
      matrix: ${{ steps.out.outputs.matrix }}
    steps:
    - name: Check
      id: check_pr_labels
      uses: Srirammkm/check-labels@main
      with:
        github-token: ${{ secrets.TOKEN }}
        labels: '["adhoc-task"]'
      continue-on-error: true
      
    - name: All Labels
      id: out
      run: |
        jobs='${{ steps.check_pr_labels.outputs.jobs }}'
        echo $jobs
        echo "matrix={\"include\":$jobs}" >> $GITHUB_OUTPUT
    - name: Print ouptut
      run: |
        echo ${{ steps.out.outputs.matrix }}
  getpod_master:
    if: github.event_name == 'push'
    name: Get POD ID
    runs-on: ubuntu-latest
    needs: check_pr_labels
    outputs:
      folder_id_master: ${{ steps.folder_id_master.outputs.pod_id}}
    steps:      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0     
          token: ${{ github.token }}    

      - name: Get Pod ID for master
        id: folder_id_master
        run: |
         pod_id=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "**/*" |  awk -F '/' '{print $1}' | sort | uniq -u)
         echo "pod_id=$pod_id" >> $GITHUB_OUTPUT
        continue-on-error: true
  job:
    name: ${{ matrix.job_name }}
    needs: [check_pr_labels]
    runs-on: ubuntu-latest #${{ needs.getpod_master.outputs.folder_id_master }}
    environment:
      name: ${{ github.event.inputs.userconfirmation }}
    timeout-minutes: 360 # 6 hour timeout
    strategy:
      matrix: ${{ fromJson(needs.check_pr_labels.outputs.matrix) }}
      max-parallel: 1 # Run jobs serially
    steps:
      - name: ${{ matrix.name }}
#         env:
#           cai_username: ${{ secrets.CAI_ADMIN }}
#           cai_password: ${{ secrets.CAI_PASSWORD }}
        run: |
          echo ${{ matrix.command }}
          echo $cai_username
          echo $cai_password
          ${{ matrix.command }}
        
