
name: "Monthly Release Pipeline"
run-name: Deploying on ${{ github.event.inputs.pod_id }}
on:
  workflow_dispatch:
    inputs:
      pod_id:
        type: choice
        description: 'Pod ID in which BPR has to trigger'     
        required: true
        options:
        - mdmnext-prod-apse1
        - mdmnext-prod-azemc1
        - mdmnext-prod-aznttjp1
        - mdmnext-prod-azusw3
        - mdmnext-prod-emw1
        - mdmnext-prod-nac1
        - mdmnext-prod-uk1
        - mdmnext-prod-use2
        - mdmnext-prod-use2s1
        - mdmnext-prod-use4
        - mdmnext-prod-use4s1
        - mdmnext-prod-use6
        - mdmnext-prod-usw3
        - mdmnext-prv-c360
        - mdmnext-prv-c360s1
        - mdmnext-prv-c360s2
        - mdmnext-stage-azusw1
        - mdmnext-stage-pod1s2
        - mdmnext-stg-pod1
        - mdmnext-stg-pod1s1
      cai_pd_status:
        description: "Is CAI Post deploy required?"
        type: boolean
        required: true
      cai_username:
        description: "CAI Username"
        required: false
      cai_password:
        type: secret
        description: "CAI Password"
        required: false
      release:
        description: "Please enter release file name"
        required: true
      userconfirmation:
        type: choice
        description: "Confirmation after each stage"
        required: true
        options:
        - manual
        - auto
        
jobs:        
  generate_matrix:
    runs-on: ubuntu-latest
    name: Generating Deployment Stages
    outputs:
      status: ${{ steps.check_pr_labels.outputs.result }}
      labels: ${{ steps.check_pr_labels.outputs.labels }}
      matrix: ${{ steps.generate.outputs.matrix }}
    steps:
    - name: Check
      id: check_pr_labels
      uses: Srirammkm/check-labels@main
      with:
        github-token: ${{ secrets.TOKEN }}
        release-file: ${{ github.event.inputs.release }}
      continue-on-error: true
      
    - name: All Labels
      id: generate
      run: |
        jobs='${{ steps.check_pr_labels.outputs.jobs }}'
        echo $jobs
        echo "matrix={\"include\":$jobs}" >> $GITHUB_OUTPUT
    - name: Print ouptut
      run: |
        echo ${{ steps.out.outputs.matrix }}
  initialize_runners:
    name: Initialize Dynamic Runners
    runs-on: ubuntu-latest
    needs: [generate_matrix]
    steps:
      - name: Initialize Runners
        env:
          TERM: xterm
        run: |
          sudo systemctl start actions.runner.infacloud-mdmnext-configs.${{runner.name}}-2.service
          sudo systemctl status actions.runner.infacloud-mdmnext-configs.${{runner.name}}-2.service
        continue-on-error: true
  source_activate:
    name: Source Activate
    runs-on: ubuntu-latest
    needs: [initialize_runners]
    outputs:
      working-directory: ${{ steps.source_activate.outputs.working-directory }}
      mail-host: ${{ steps.source_activate.outputs.mail-host }}
    steps:      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0     
          token: ${{ github.token }}   
          
      - name: Source Activate
        id: source_activate
        env:
          folder_id: ${{ github.event.inputs.pod_id }}
          TERM: xterm
        run: | 
          sudo chmod -R 777 ${{ github.workspace }}
          cat <<EOF | bash
          [[ ":$PATH:" != *":\$(pwd):"* ]] && PATH="\$(pwd):${PATH}"
          source activate "$folder_id" 
          ./mops build mdm
          working_dir="build/$(cat "$folder_id"/env | grep "POD_ID" | awk -F "=" '{print $2}' | tr -d '"')/mdm"
          mail_host-"$(cat "$folder_id"/mdm/resources/helm/common-config-params.yaml | grep "mail_host" | awk '{print $2}' )"
          echo "working-directory=$working_dir" >> $GITHUB_OUTPUT
          echo "mail-host=$mail_host" >> $GITHUB_OUTPUT
          EOF
        continue-on-error: true
        
  cai_pd:
    if: ${{ github.event.inputs.cai_pd_status }}
    name: CAI Post Deployment
    runs-on: ubuntu-latest
    needs: [source_activate]
    steps:
      - name: CAI Post Deployment
        env:
          folder_id: ${{ github.event.inputs.pod_id }}
          working-directory: ${{ needs.source_activate.outputs.working-directory }}
          CAI_ADMIN_USERNAME: ${{ github.event.inputs.cai_username }}
          CAI_ADMIN_PASSWORD: ${{ github.event.inputs.cai_password }}
          TERM: xterm
        run: |
          source activate "$folder_id" 
          cd ${{ env.working-directory}}
          ./bin/tools/run-cai-post-deploy.sh
        continue-on-error: true

  deployment_stages:
    name: ${{ matrix.job_name }}
    needs: [source_activate,cai_pd,generate_matrix]
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.release }}-${{ github.event.inputs.userconfirmation }}
    timeout-minutes: 360 # 6 hour timeout
    strategy:
      matrix: ${{ fromJson(needs.generate_matrix.outputs.matrix) }}
      max-parallel: 1 # Run jobs serially
    steps:
      - name: ${{ matrix.name }}
        env:
          TERM: xterm
          folder_id: ${{ github.event.inputs.pod_id }}
          working-directory: ${{ needs.source_activate.outputs.working-directory }}
        run: |
          source activate "$folder_id" 
          cd ${{ env.working-directory}}
          ${{ matrix.command }}
        
